version: 0.2
phases:
  install:
    commands:
        # Install packages or any pre-reqs in this phase
        # Upgrading SAM CLI to LAtest Version 1

        - pip install --upgrade pip
        - pip3 install --upgrade awscli
        - aws cloudformation deploy --template-file ./templates/cloudfront-distribution-withcertificate.yaml --stack-name lilacpatient-app-$ENV_STAGE-cloudfront-distributionwithcertificate --s3-bucket $DEPLOYMENT_BUCKET_NAME --parameter-overrides $(cat lilacpatient-app-cloudfront-distributionwithcertificate.$ENV_STAGE.properties) --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
        - npm i mpm@latest -g

  pre_build:
    commands:
        - echo pre_build Phase
        - npm install -y
        - npm run build
        # - npm run build:$NODE_ENV

  build:
    commands:
      # use Build phase to build your artifacts (compile, etc.)
      - aws cloudformation deploy --template-file ./templates/cloudfront-s3-bucket.yaml --stack-name lilacpatient-app-$ENV_STAGE-cloudfront-s3-bucket --s3-bucket $DEPLOYMENT_BUCKET_NAME --parameter-overrides $(cat lilacpatient-app-cloudfront-s3-bucket.$ENV_STAGE.properties) --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      

  post_build:
    commands:
      - echo post build phase
      - aws s3 rm s3://lilacpatientweb --recursive
      - echo PostDelete Phase
      - aws s3 sync ./public s3://lilacpatientweb --delete

# artifacts:
#   files:
#     - template.yaml