version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 14
    command:
        # Install packages or any pre-reqs in this phase
        # Upgrading SAM CLI to LAtest Version 1
        - pip3 install --upgrade awscli

  build:
    commands:
      # use Build phase to build your artifacts (compile, etc.)
      # - aws cloudformation deploy --template-file ./templates/cloudfront-s3-bucket.yaml --stack-name mydemoproject-app-$ENV_STAGE-cloudfront-s3-bucket --s3-bucket $DEPLOYMENT_BUCKET_NAME --parameter-overrides $(cat mydemoproject-app-cloudfront-s3-bucket.$ENV_STAGE.properties) --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudformation deploy --template-file ./templates/cloudfront-s3-bucket.yaml --stack-name mydemoproject-app-$ENV_STAGE-cloudfront-s3-bucketv1 --s3-bucket $DEPLOYMENT_BUCKET_NAME --parameter-overrides $(cat mydemoproject-app-cloudfront-s3-bucketv1.$ENV_STAGE.properties) --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      # - aws cloudformation deploy --template-file ./templates/cloudfront-distribution.yaml --stack-name mydemoproject-app-$ENV_STAGE-cloudfront-distribution --s3-bucket $DEPLOYMENT_BUCKET_NAME --parameter-overrides $(cat cloudfront-distribution.$ENV_STAGE.properties) --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudformation deploy --template-file ./templates/cloudfront-distribution_updated.yaml --stack-name mydemoproject-app-$ENV_STAGE-cloudfront-distribution_updated.yaml --s3-bucket $DEPLOYMENT_BUCKET_NAME --parameter-overrides $(cat cloudfront-distribution_updated.yaml.$ENV_STAGE.properties) --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset

# artifacts:
#   files:
#     - template.yaml
